version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: CreditCalculator/Dockerfile
    ports:
      - "8181:8080"

  tests:
    build:
      context: .
      dockerfile: CreditCalculator.Tests/Dockerfile
    profiles:
      - test
